version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-server
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
file_exists_behavior: OVERWRITE
