version: 0.2
env:
  variables:
    APP_NAME: "express-app"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo install process started
  build:
    commands:
      - echo Running process started
  post_build:
    commands:
      - echo build process finished